cineguard:
  log-level: "debug"
  serve:
    address: "127.0.0.1"
    port: "8080"
  database:
    type: postgres
    address: "0.0.0.0"
    port: "5432"
    username: "myuser"
    password: "mypassword"
